wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
architecture:
  desc: null
  value: REINFORCE
dataset:
  desc: null
  value: CartPole
episodes:
  desc: null
  value: 2000
gamma:
  desc: null
  value: 0.99
episode_max_len:
  desc: null
  value: 500
N:
  desc: null
  value: 100
temperature:
  desc: null
  value: 20
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1715428059.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.11.9
      5: 0.16.6
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
